services:
  api:
    platform: linux/amd64
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env.prod
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: /bin/sh -c "npm run migrate up && npm run start"

  db:
    image: "postgres"
    environment:
      POSTGRES_DB: emobility-prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - emobility-prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  emobility-prod: